M48
; DRILL file KiCad 10.0.6 date 2026-09-30T18:30:04
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-30T18:30:04+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.250
%
G90
G05
T1
X75.6Y-113.99
X75.6Y-126.8
T2
X74.0Y-45.0
X74.0Y-135.0
X226.0Y-45.0
X226.0Y-135.0
T3
X79.31Y-52.94
X79.31Y-64.37
M30
